# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\Python Projects\Pygui\Pygui\win.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Window(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(770, 514)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setItalic(False)
        MainWindow.setFont(font)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.TabWidget = QtGui.QTabWidget(self.centralwidget)
        self.TabWidget.setEnabled(True)
        self.TabWidget.setGeometry(QtCore.QRect(10, 10, 751, 431))
        self.TabWidget.setAutoFillBackground(False)
        self.TabWidget.setTabShape(QtGui.QTabWidget.Triangular)
        self.TabWidget.setObjectName(_fromUtf8("TabWidget"))
        self.TabInput = QtGui.QWidget()
        self.TabInput.setObjectName(_fromUtf8("TabInput"))
        self.label = QtGui.QLabel(self.TabInput)
        self.label.setGeometry(QtCore.QRect(20, 20, 231, 21))
        self.label.setObjectName(_fromUtf8("label"))
        self.RdoDirected = QtGui.QRadioButton(self.TabInput)
        self.RdoDirected.setGeometry(QtCore.QRect(310, 20, 151, 17))
        self.RdoDirected.setObjectName(_fromUtf8("RdoDirected"))
        self.RdoUndirected = QtGui.QRadioButton(self.TabInput)
        self.RdoUndirected.setGeometry(QtCore.QRect(520, 20, 151, 17))
        self.RdoUndirected.setObjectName(_fromUtf8("RdoUndirected"))
        self.line = QtGui.QFrame(self.TabInput)
        self.line.setGeometry(QtCore.QRect(20, 40, 691, 16))
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.ChkWeighted = QtGui.QCheckBox(self.TabInput)
        self.ChkWeighted.setGeometry(QtCore.QRect(20, 60, 631, 17))
        self.ChkWeighted.setObjectName(_fromUtf8("ChkWeighted"))
        self.line_2 = QtGui.QFrame(self.TabInput)
        self.line_2.setGeometry(QtCore.QRect(20, 80, 691, 16))
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.pushButton = QtGui.QPushButton(self.TabInput)
        self.pushButton.setGeometry(QtCore.QRect(20, 110, 201, 31))
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.LblNetworksDirectory = QtGui.QLabel(self.TabInput)
        self.LblNetworksDirectory.setGeometry(QtCore.QRect(20, 190, 691, 21))
        self.LblNetworksDirectory.setStyleSheet(_fromUtf8("color:blue;font-style:italic;"))
        self.LblNetworksDirectory.setText(_fromUtf8(""))
        self.LblNetworksDirectory.setObjectName(_fromUtf8("LblNetworksDirectory"))
        self.groupBox = QtGui.QGroupBox(self.TabInput)
        self.groupBox.setGeometry(QtCore.QRect(20, 290, 691, 71))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.RdoGML = QtGui.QRadioButton(self.groupBox)
        self.RdoGML.setGeometry(QtCore.QRect(10, 30, 101, 17))
        self.RdoGML.setObjectName(_fromUtf8("RdoGML"))
        self.RdoGraphML = QtGui.QRadioButton(self.groupBox)
        self.RdoGraphML.setGeometry(QtCore.QRect(180, 30, 141, 17))
        self.RdoGraphML.setObjectName(_fromUtf8("RdoGraphML"))
        self.RdoPajek = QtGui.QRadioButton(self.groupBox)
        self.RdoPajek.setGeometry(QtCore.QRect(380, 30, 101, 17))
        self.RdoPajek.setObjectName(_fromUtf8("RdoPajek"))
        self.RdoEdgeList = QtGui.QRadioButton(self.groupBox)
        self.RdoEdgeList.setGeometry(QtCore.QRect(550, 30, 121, 17))
        self.RdoEdgeList.setObjectName(_fromUtf8("RdoEdgeList"))
        self.label_3 = QtGui.QLabel(self.TabInput)
        self.label_3.setGeometry(QtCore.QRect(20, 160, 91, 21))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.ChkFilesAreGrouped = QtGui.QCheckBox(self.TabInput)
        self.ChkFilesAreGrouped.setGeometry(QtCore.QRect(20, 240, 231, 17))
        self.ChkFilesAreGrouped.setObjectName(_fromUtf8("ChkFilesAreGrouped"))
        self.TabWidget.addTab(self.TabInput, _fromUtf8(""))
        self.TabOptions = QtGui.QWidget()
        self.TabOptions.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.TabOptions.setObjectName(_fromUtf8("TabOptions"))
        self.line_4 = QtGui.QFrame(self.TabOptions)
        self.line_4.setGeometry(QtCore.QRect(20, 110, 701, 16))
        self.line_4.setFrameShape(QtGui.QFrame.HLine)
        self.line_4.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_4.setObjectName(_fromUtf8("line_4"))
        self.ChkLccSize = QtGui.QCheckBox(self.TabOptions)
        self.ChkLccSize.setGeometry(QtCore.QRect(520, 90, 161, 17))
        self.ChkLccSize.setObjectName(_fromUtf8("ChkLccSize"))
        self.ChkMeanCloCentrality = QtGui.QCheckBox(self.TabOptions)
        self.ChkMeanCloCentrality.setGeometry(QtCore.QRect(520, 130, 161, 17))
        self.ChkMeanCloCentrality.setObjectName(_fromUtf8("ChkMeanCloCentrality"))
        self.ChkMeanDegreeCentrality = QtGui.QCheckBox(self.TabOptions)
        self.ChkMeanDegreeCentrality.setEnabled(False)
        self.ChkMeanDegreeCentrality.setGeometry(QtCore.QRect(20, 130, 161, 17))
        self.ChkMeanDegreeCentrality.setChecked(True)
        self.ChkMeanDegreeCentrality.setObjectName(_fromUtf8("ChkMeanDegreeCentrality"))
        self.line_5 = QtGui.QFrame(self.TabOptions)
        self.line_5.setGeometry(QtCore.QRect(20, 150, 701, 16))
        self.line_5.setFrameShape(QtGui.QFrame.HLine)
        self.line_5.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_5.setObjectName(_fromUtf8("line_5"))
        self.ChkMeanCCSize = QtGui.QCheckBox(self.TabOptions)
        self.ChkMeanCCSize.setGeometry(QtCore.QRect(20, 210, 211, 17))
        self.ChkMeanCCSize.setObjectName(_fromUtf8("ChkMeanCCSize"))
        self.ChkDenisty = QtGui.QCheckBox(self.TabOptions)
        self.ChkDenisty.setGeometry(QtCore.QRect(520, 210, 161, 17))
        self.ChkDenisty.setObjectName(_fromUtf8("ChkDenisty"))
        self.chkNodeCount = QtGui.QCheckBox(self.TabOptions)
        self.chkNodeCount.setEnabled(False)
        self.chkNodeCount.setGeometry(QtCore.QRect(20, 90, 161, 17))
        self.chkNodeCount.setChecked(True)
        self.chkNodeCount.setObjectName(_fromUtf8("chkNodeCount"))
        self.chkEdgeCount = QtGui.QCheckBox(self.TabOptions)
        self.chkEdgeCount.setEnabled(False)
        self.chkEdgeCount.setGeometry(QtCore.QRect(270, 90, 161, 17))
        self.chkEdgeCount.setChecked(True)
        self.chkEdgeCount.setObjectName(_fromUtf8("chkEdgeCount"))
        self.line_6 = QtGui.QFrame(self.TabOptions)
        self.line_6.setGeometry(QtCore.QRect(20, 230, 701, 16))
        self.line_6.setFrameShape(QtGui.QFrame.HLine)
        self.line_6.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_6.setObjectName(_fromUtf8("line_6"))
        self.ChkTransitivity = QtGui.QCheckBox(self.TabOptions)
        self.ChkTransitivity.setGeometry(QtCore.QRect(270, 210, 161, 17))
        self.ChkTransitivity.setObjectName(_fromUtf8("ChkTransitivity"))
        self.ChkClusteringCoefficient = QtGui.QCheckBox(self.TabOptions)
        self.ChkClusteringCoefficient.setGeometry(QtCore.QRect(520, 170, 201, 17))
        self.ChkClusteringCoefficient.setObjectName(_fromUtf8("ChkClusteringCoefficient"))
        self.ChkMeanLoadCentrality = QtGui.QCheckBox(self.TabOptions)
        self.ChkMeanLoadCentrality.setGeometry(QtCore.QRect(20, 170, 161, 17))
        self.ChkMeanLoadCentrality.setObjectName(_fromUtf8("ChkMeanLoadCentrality"))
        self.ChkMeanCommCentrality = QtGui.QCheckBox(self.TabOptions)
        self.ChkMeanCommCentrality.setGeometry(QtCore.QRect(270, 170, 211, 17))
        self.ChkMeanCommCentrality.setObjectName(_fromUtf8("ChkMeanCommCentrality"))
        self.line_7 = QtGui.QFrame(self.TabOptions)
        self.line_7.setGeometry(QtCore.QRect(20, 270, 701, 16))
        self.line_7.setFrameShape(QtGui.QFrame.HLine)
        self.line_7.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_7.setObjectName(_fromUtf8("line_7"))
        self.ChkAvgDegreeConnectivity = QtGui.QCheckBox(self.TabOptions)
        self.ChkAvgDegreeConnectivity.setGeometry(QtCore.QRect(520, 250, 181, 17))
        self.ChkAvgDegreeConnectivity.setObjectName(_fromUtf8("ChkAvgDegreeConnectivity"))
        self.label_2 = QtGui.QLabel(self.TabOptions)
        self.label_2.setGeometry(QtCore.QRect(20, 30, 691, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setItalic(False)
        self.label_2.setFont(font)
        self.label_2.setAcceptDrops(False)
        self.label_2.setLineWidth(2)
        self.label_2.setTextFormat(QtCore.Qt.PlainText)
        self.label_2.setScaledContents(False)
        self.label_2.setWordWrap(True)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.ChkMeanBetCentrality = QtGui.QCheckBox(self.TabOptions)
        self.ChkMeanBetCentrality.setGeometry(QtCore.QRect(270, 130, 211, 17))
        self.ChkMeanBetCentrality.setObjectName(_fromUtf8("ChkMeanBetCentrality"))
        self.ChkKatzCentrality = QtGui.QCheckBox(self.TabOptions)
        self.ChkKatzCentrality.setGeometry(QtCore.QRect(520, 290, 161, 17))
        self.ChkKatzCentrality.setObjectName(_fromUtf8("ChkKatzCentrality"))
        self.ChkDegreeAssortativityCoefficient = QtGui.QCheckBox(self.TabOptions)
        self.ChkDegreeAssortativityCoefficient.setGeometry(QtCore.QRect(270, 250, 221, 17))
        self.ChkDegreeAssortativityCoefficient.setObjectName(_fromUtf8("ChkDegreeAssortativityCoefficient"))
        self.ChkAvgCFClosCentrality = QtGui.QCheckBox(self.TabOptions)
        self.ChkAvgCFClosCentrality.setGeometry(QtCore.QRect(20, 290, 251, 17))
        self.ChkAvgCFClosCentrality.setObjectName(_fromUtf8("ChkAvgCFClosCentrality"))
        self.ChkMaxCliqueSize = QtGui.QCheckBox(self.TabOptions)
        self.ChkMaxCliqueSize.setGeometry(QtCore.QRect(20, 250, 161, 17))
        self.ChkMaxCliqueSize.setObjectName(_fromUtf8("ChkMaxCliqueSize"))
        self.line_8 = QtGui.QFrame(self.TabOptions)
        self.line_8.setGeometry(QtCore.QRect(20, 190, 701, 16))
        self.line_8.setFrameShape(QtGui.QFrame.HLine)
        self.line_8.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_8.setObjectName(_fromUtf8("line_8"))
        self.ChkAvgEccentricity = QtGui.QCheckBox(self.TabOptions)
        self.ChkAvgEccentricity.setGeometry(QtCore.QRect(520, 330, 161, 17))
        self.ChkAvgEccentricity.setObjectName(_fromUtf8("ChkAvgEccentricity"))
        self.ChkEigenvectorCentrality = QtGui.QCheckBox(self.TabOptions)
        self.ChkEigenvectorCentrality.setGeometry(QtCore.QRect(270, 290, 221, 17))
        self.ChkEigenvectorCentrality.setObjectName(_fromUtf8("ChkEigenvectorCentrality"))
        self.ChkNetDiameter = QtGui.QCheckBox(self.TabOptions)
        self.ChkNetDiameter.setGeometry(QtCore.QRect(270, 330, 161, 17))
        self.ChkNetDiameter.setObjectName(_fromUtf8("ChkNetDiameter"))
        self.ChkNumberOfConnectedComponents = QtGui.QCheckBox(self.TabOptions)
        self.ChkNumberOfConnectedComponents.setGeometry(QtCore.QRect(20, 330, 231, 17))
        self.ChkNumberOfConnectedComponents.setObjectName(_fromUtf8("ChkNumberOfConnectedComponents"))
        self.line_9 = QtGui.QFrame(self.TabOptions)
        self.line_9.setGeometry(QtCore.QRect(20, 310, 701, 16))
        self.line_9.setFrameShape(QtGui.QFrame.HLine)
        self.line_9.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_9.setObjectName(_fromUtf8("line_9"))
        self.line_19 = QtGui.QFrame(self.TabOptions)
        self.line_19.setGeometry(QtCore.QRect(20, 350, 701, 16))
        self.line_19.setFrameShape(QtGui.QFrame.HLine)
        self.line_19.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_19.setObjectName(_fromUtf8("line_19"))
        self.ChkAvgPagerank = QtGui.QCheckBox(self.TabOptions)
        self.ChkAvgPagerank.setGeometry(QtCore.QRect(270, 370, 161, 17))
        self.ChkAvgPagerank.setObjectName(_fromUtf8("ChkAvgPagerank"))
        self.ChkAvgShortestPath = QtGui.QCheckBox(self.TabOptions)
        self.ChkAvgShortestPath.setGeometry(QtCore.QRect(520, 370, 161, 17))
        self.ChkAvgShortestPath.setObjectName(_fromUtf8("ChkAvgShortestPath"))
        self.ChkNetworkRadius = QtGui.QCheckBox(self.TabOptions)
        self.ChkNetworkRadius.setGeometry(QtCore.QRect(20, 370, 231, 17))
        self.ChkNetworkRadius.setObjectName(_fromUtf8("ChkNetworkRadius"))
        self.line_4.raise_()
        self.ChkLccSize.raise_()
        self.ChkMeanCloCentrality.raise_()
        self.ChkMeanDegreeCentrality.raise_()
        self.line_5.raise_()
        self.ChkMeanCCSize.raise_()
        self.ChkDenisty.raise_()
        self.chkEdgeCount.raise_()
        self.line_6.raise_()
        self.ChkTransitivity.raise_()
        self.ChkClusteringCoefficient.raise_()
        self.ChkMeanLoadCentrality.raise_()
        self.ChkMeanCommCentrality.raise_()
        self.line_7.raise_()
        self.ChkAvgDegreeConnectivity.raise_()
        self.label_2.raise_()
        self.ChkMeanBetCentrality.raise_()
        self.ChkKatzCentrality.raise_()
        self.ChkDegreeAssortativityCoefficient.raise_()
        self.ChkMaxCliqueSize.raise_()
        self.line_8.raise_()
        self.ChkAvgEccentricity.raise_()
        self.ChkEigenvectorCentrality.raise_()
        self.ChkNetDiameter.raise_()
        self.ChkNumberOfConnectedComponents.raise_()
        self.line_9.raise_()
        self.line_19.raise_()
        self.ChkAvgPagerank.raise_()
        self.ChkAvgShortestPath.raise_()
        self.ChkNetworkRadius.raise_()
        self.ChkAvgCFClosCentrality.raise_()
        self.chkNodeCount.raise_()
        self.TabWidget.addTab(self.TabOptions, _fromUtf8(""))
        self.TabOutput = QtGui.QWidget()
        self.TabOutput.setObjectName(_fromUtf8("TabOutput"))
        self.ChkStatisticAnalysisOfGroups = QtGui.QCheckBox(self.TabOutput)
        self.ChkStatisticAnalysisOfGroups.setGeometry(QtCore.QRect(40, 200, 651, 17))
        self.ChkStatisticAnalysisOfGroups.setObjectName(_fromUtf8("ChkStatisticAnalysisOfGroups"))
        self.ChkTsv = QtGui.QCheckBox(self.TabOutput)
        self.ChkTsv.setEnabled(False)
        self.ChkTsv.setGeometry(QtCore.QRect(40, 50, 661, 17))
        self.ChkTsv.setChecked(True)
        self.ChkTsv.setObjectName(_fromUtf8("ChkTsv"))
        self.label_7 = QtGui.QLabel(self.TabOutput)
        self.label_7.setGeometry(QtCore.QRect(60, 80, 671, 31))
        self.label_7.setStyleSheet(_fromUtf8("font-style:italic;font-size:13px;color:gray;"))
        self.label_7.setWordWrap(True)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.ChkTsv_2 = QtGui.QCheckBox(self.TabOutput)
        self.ChkTsv_2.setEnabled(False)
        self.ChkTsv_2.setGeometry(QtCore.QRect(40, 130, 661, 17))
        self.ChkTsv_2.setChecked(True)
        self.ChkTsv_2.setObjectName(_fromUtf8("ChkTsv_2"))
        self.label_10 = QtGui.QLabel(self.TabOutput)
        self.label_10.setGeometry(QtCore.QRect(60, 150, 671, 31))
        self.label_10.setStyleSheet(_fromUtf8("font-style:italic;font-size:13px;color:gray;"))
        self.label_10.setWordWrap(True)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.ChkStatisticAnalysisOfAllNetworks = QtGui.QCheckBox(self.TabOutput)
        self.ChkStatisticAnalysisOfAllNetworks.setGeometry(QtCore.QRect(40, 240, 651, 17))
        self.ChkStatisticAnalysisOfAllNetworks.setObjectName(_fromUtf8("ChkStatisticAnalysisOfAllNetworks"))
        self.TabWidget.addTab(self.TabOutput, _fromUtf8(""))
        self.TabHelp = QtGui.QWidget()
        self.TabHelp.setObjectName(_fromUtf8("TabHelp"))
        self.label_4 = QtGui.QLabel(self.TabHelp)
        self.label_4.setGeometry(QtCore.QRect(60, 30, 501, 301))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.TabWidget.addTab(self.TabHelp, _fromUtf8(""))
        self.pbar = QtGui.QProgressBar(self.centralwidget)
        self.pbar.setGeometry(QtCore.QRect(10, 470, 591, 23))
        self.pbar.setStyleSheet(_fromUtf8("color:green;"))
        self.pbar.setProperty("value", 24)
        self.pbar.setObjectName(_fromUtf8("pbar"))
        self.BtnStart = QtGui.QPushButton(self.centralwidget)
        self.BtnStart.setGeometry(QtCore.QRect(610, 470, 151, 23))
        self.BtnStart.setObjectName(_fromUtf8("BtnStart"))
        self.LblWorking = QtGui.QLabel(self.centralwidget)
        self.LblWorking.setGeometry(QtCore.QRect(15, 450, 111, 16))
        self.LblWorking.setStyleSheet(_fromUtf8("color:green;font-weight:bold;font-size:13px;"))
        self.LblWorking.setObjectName(_fromUtf8("LblWorking"))
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.MnuExit = QtGui.QAction(MainWindow)
        self.MnuExit.setObjectName(_fromUtf8("MnuExit"))
        self.actionHelp = QtGui.QAction(MainWindow)
        self.actionHelp.setObjectName(_fromUtf8("actionHelp"))
        self.actionAbout = QtGui.QAction(MainWindow)
        self.actionAbout.setObjectName(_fromUtf8("actionAbout"))

        self.retranslateUi(MainWindow)
        self.TabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.RdoDirected, self.RdoUndirected)
        MainWindow.setTabOrder(self.RdoUndirected, self.ChkWeighted)
        MainWindow.setTabOrder(self.ChkWeighted, self.pushButton)
        MainWindow.setTabOrder(self.pushButton, self.ChkFilesAreGrouped)
        MainWindow.setTabOrder(self.ChkFilesAreGrouped, self.RdoGML)
        MainWindow.setTabOrder(self.RdoGML, self.RdoGraphML)
        MainWindow.setTabOrder(self.RdoGraphML, self.RdoPajek)
        MainWindow.setTabOrder(self.RdoPajek, self.RdoEdgeList)
        MainWindow.setTabOrder(self.RdoEdgeList, self.chkNodeCount)
        MainWindow.setTabOrder(self.chkNodeCount, self.chkEdgeCount)
        MainWindow.setTabOrder(self.chkEdgeCount, self.ChkLccSize)
        MainWindow.setTabOrder(self.ChkLccSize, self.ChkMeanDegreeCentrality)
        MainWindow.setTabOrder(self.ChkMeanDegreeCentrality, self.ChkMeanBetCentrality)
        MainWindow.setTabOrder(self.ChkMeanBetCentrality, self.ChkMeanCloCentrality)
        MainWindow.setTabOrder(self.ChkMeanCloCentrality, self.ChkMeanLoadCentrality)
        MainWindow.setTabOrder(self.ChkMeanLoadCentrality, self.ChkMeanCommCentrality)
        MainWindow.setTabOrder(self.ChkMeanCommCentrality, self.ChkClusteringCoefficient)
        MainWindow.setTabOrder(self.ChkClusteringCoefficient, self.ChkMeanCCSize)
        MainWindow.setTabOrder(self.ChkMeanCCSize, self.ChkTransitivity)
        MainWindow.setTabOrder(self.ChkTransitivity, self.ChkDenisty)
        MainWindow.setTabOrder(self.ChkDenisty, self.ChkMaxCliqueSize)
        MainWindow.setTabOrder(self.ChkMaxCliqueSize, self.ChkDegreeAssortativityCoefficient)
        MainWindow.setTabOrder(self.ChkDegreeAssortativityCoefficient, self.ChkAvgDegreeConnectivity)
        MainWindow.setTabOrder(self.ChkAvgDegreeConnectivity, self.ChkAvgCFClosCentrality)
        MainWindow.setTabOrder(self.ChkAvgCFClosCentrality, self.ChkEigenvectorCentrality)
        MainWindow.setTabOrder(self.ChkEigenvectorCentrality, self.ChkKatzCentrality)
        MainWindow.setTabOrder(self.ChkKatzCentrality, self.ChkNumberOfConnectedComponents)
        MainWindow.setTabOrder(self.ChkNumberOfConnectedComponents, self.ChkNetDiameter)
        MainWindow.setTabOrder(self.ChkNetDiameter, self.ChkAvgEccentricity)
        MainWindow.setTabOrder(self.ChkAvgEccentricity, self.ChkNetworkRadius)
        MainWindow.setTabOrder(self.ChkNetworkRadius, self.ChkAvgPagerank)
        MainWindow.setTabOrder(self.ChkAvgPagerank, self.ChkAvgShortestPath)
        MainWindow.setTabOrder(self.ChkAvgShortestPath, self.ChkTsv)
        MainWindow.setTabOrder(self.ChkTsv, self.ChkTsv_2)
        MainWindow.setTabOrder(self.ChkTsv_2, self.ChkStatisticAnalysisOfGroups)
        MainWindow.setTabOrder(self.ChkStatisticAnalysisOfGroups, self.ChkStatisticAnalysisOfAllNetworks)
        MainWindow.setTabOrder(self.ChkStatisticAnalysisOfAllNetworks, self.BtnStart)
        MainWindow.setTabOrder(self.BtnStart, self.TabWidget)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "CatbNet", None))
        self.label.setText(_translate("MainWindow", "Networks Type:", None))
        self.RdoDirected.setText(_translate("MainWindow", "Directed Network", None))
        self.RdoUndirected.setText(_translate("MainWindow", "Undirected Network", None))
        self.ChkWeighted.setText(_translate("MainWindow", "Networks are weighted", None))
        self.pushButton.setText(_translate("MainWindow", "Select Networks Directory", None))
        self.groupBox.setTitle(_translate("MainWindow", "Input Network file format type", None))
        self.RdoGML.setText(_translate("MainWindow", "GML (.gml)", None))
        self.RdoGraphML.setText(_translate("MainWindow", "GraphML (.graphml)", None))
        self.RdoPajek.setText(_translate("MainWindow", "Pajek (.net)", None))
        self.RdoEdgeList.setText(_translate("MainWindow", "Edge List (.el)", None))
        self.label_3.setText(_translate("MainWindow", "Selected Path:", None))
        self.ChkFilesAreGrouped.setText(_translate("MainWindow", "Input files are classified in groups", None))
        self.TabWidget.setTabText(self.TabWidget.indexOf(self.TabInput), _translate("MainWindow", "Input", None))
        self.ChkLccSize.setText(_translate("MainWindow", "LCC size", None))
        self.ChkMeanCloCentrality.setText(_translate("MainWindow", "Avg. Closness Centrality", None))
        self.ChkMeanDegreeCentrality.setText(_translate("MainWindow", "Avg. Degree Centrality", None))
        self.ChkMeanCCSize.setText(_translate("MainWindow", "Avg. Connected Component size", None))
        self.ChkDenisty.setText(_translate("MainWindow", "Density", None))
        self.chkNodeCount.setText(_translate("MainWindow", "Number of Nodes", None))
        self.chkEdgeCount.setText(_translate("MainWindow", "Number of Edges", None))
        self.ChkTransitivity.setText(_translate("MainWindow", "Transitivity", None))
        self.ChkClusteringCoefficient.setText(_translate("MainWindow", "Network Clustering Coefficient", None))
        self.ChkMeanLoadCentrality.setText(_translate("MainWindow", "Avg. Load Centrality", None))
        self.ChkMeanCommCentrality.setText(_translate("MainWindow", "Avg. Communicability Centrality", None))
        self.ChkAvgDegreeConnectivity.setText(_translate("MainWindow", "Avg. Degree Connectivity", None))
        self.label_2.setText(_translate("MainWindow", "Select all options that you want to be calculated for all networks. Execution time will depend on number of items you select.", None))
        self.ChkMeanBetCentrality.setText(_translate("MainWindow", "Avg. Betweenness Centrality", None))
        self.ChkKatzCentrality.setText(_translate("MainWindow", "Avg. Katz Centrality", None))
        self.ChkDegreeAssortativityCoefficient.setText(_translate("MainWindow", "Degree Assortativity Coefficient", None))
        self.ChkAvgCFClosCentrality.setText(_translate("MainWindow", "Avg. Current-Flow Closeness Centrality", None))
        self.ChkMaxCliqueSize.setText(_translate("MainWindow", "Max Clique Size", None))
        self.ChkAvgEccentricity.setText(_translate("MainWindow", "Avg. Eccentricity", None))
        self.ChkEigenvectorCentrality.setText(_translate("MainWindow", "Network Eigenvector Centrality", None))
        self.ChkNetDiameter.setText(_translate("MainWindow", "Network Diameter", None))
        self.ChkNumberOfConnectedComponents.setText(_translate("MainWindow", "Number of Connected Components", None))
        self.ChkAvgPagerank.setText(_translate("MainWindow", "Avg. PageRank", None))
        self.ChkAvgShortestPath.setText(_translate("MainWindow", "Avg. Shortest Path", None))
        self.ChkNetworkRadius.setText(_translate("MainWindow", "Radius", None))
        self.TabWidget.setTabText(self.TabWidget.indexOf(self.TabOptions), _translate("MainWindow", "Options", None))
        self.ChkStatisticAnalysisOfGroups.setText(_translate("MainWindow", "One-way ANOVA test / Boxplot Comparision for Groups of Networks", None))
        self.ChkTsv.setText(_translate("MainWindow", "Tab Seperated Values (.tsv) result file", None))
        self.label_7.setText(_translate("MainWindow", "<html><head/><body><p>result for all items selected in \'Options\' tab will be presented in a single .tsv file. each line of file demonstrating a single network</p></body></html>", None))
        self.ChkTsv_2.setText(_translate("MainWindow", "Tab Seperated Values (.tsv) result file for nodes", None))
        self.label_10.setText(_translate("MainWindow", "<html><head/><body><p>a tab seprated file for nodes attributes in all networks</p></body></html>", None))
        self.ChkStatisticAnalysisOfAllNetworks.setText(_translate("MainWindow", "One-way ANOVA test / Boxplot Comparision for all Networks", None))
        self.TabWidget.setTabText(self.TabWidget.indexOf(self.TabOutput), _translate("MainWindow", "Output", None))
        self.label_4.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600; text-decoration: underline;\">CatbNet</span></p><p align=\"justify\"><span style=\" font-size:11pt;\">Tools for comparing and analyzing the topologies of biological networks.</span></p><p align=\"justify\"><span style=\" font-size:11pt;\">Github page: </span><a href=\"http://github.com/ehpo/CatbNet\"><span style=\" font-size:10pt; text-decoration: underline; color:#0000ff;\">http://github.com/ehpo/CatbNet</span></a></p><p align=\"justify\"><br/><span style=\" font-size:11pt; text-decoration: underline;\">Ehsan Pournoor</span></p><p align=\"justify\"><span style=\" font-size:11pt; color:#474747;\">Email: e.pournoor@ut.ac.ir</span></p><p align=\"justify\"><span style=\" font-size:11pt; color:#474747;\">Laboratory of Systems Biology and Bioinformatics (LBB)</span></p><p align=\"justify\"><span style=\" font-size:11pt; color:#474747;\">Institute of Biochemistry and Biophysics (IBB)</span></p><p align=\"justify\"><span style=\" font-size:11pt; color:#474747;\">University of Tehran</span></p></body></html>", None))
        self.TabWidget.setTabText(self.TabWidget.indexOf(self.TabHelp), _translate("MainWindow", "Help", None))
        self.BtnStart.setText(_translate("MainWindow", "Start", None))
        self.LblWorking.setText(_translate("MainWindow", "Working ...", None))
        self.MnuExit.setText(_translate("MainWindow", "Exit", None))
        self.actionHelp.setText(_translate("MainWindow", "Help", None))
        self.actionAbout.setText(_translate("MainWindow", "About ", None))

